from datetime import timedelta, datetime
from dateutil.relativedelta import relativedelta
import pytz
from odoo import models, fields, api, _
from odoo.addons.calendar.models.calendar_recurrence import (
    weekday_to_field,
    RRULE_TYPE_SELECTION,
    END_TYPE_SELECTION,
    MONTH_BY_SELECTION,
    WEEKDAY_SELECTION,
    BYDAY_SELECTION
)


class Contract(models.Model):
    _inherit = "contract.contract"

    sale_id = fields.Many2one(comodel_name='sale.order')
    sale_order_line_id = fields.Many2one(comodel_name='sale.order.line')


    @api.depends("sale_id")
    def _compute_sales_count(self):
        for rec in self:
            if rec.sale_id:
                rec.sale_count = len(rec.sale_id)
            else:
                rec.sale_count = 0


    sale_count = fields.Integer(string="Sale Count", compute=_compute_sales_count)


    def action_view_sales(self):
        self.ensure_one()
        ctx = dict(self.env.context)

        action = {
            "type": "ir.actions.act_window",
            "name": "Contract Sale",
            "res_model": "sale.order",
            "view_mode": "form",
            "domain": [("id", "=", self.sale_id.id)],
            'res_id': self.sale_id.id,
            "context": ctx,
        }
        return action


    # def get_first_invoice_date(self):
    #     """Return the date of the first invoice"""
    #     today = fields.Date.from_string(fields.Date.today())
    #     time = fields.Date.from_string(self.recurring_next_date)
    #     if self.recurring_rule_type == 'daily':
    #         deltaT = relativedelta(days=self.recurring_interval)
    #     elif self.recurring_rule_type == 'weekly':
    #         deltaT = relativedelta(weeks=self.recurring_interval)
    #     elif self.recurring_rule_type == 'monthly':
    #         deltaT = relativedelta(months=self.recurring_interval)
    #     elif self.recurring_rule_type == 'yearly':
    #         deltaT = relativedelta(years=self.recurring_interval)
    #     while time < today:
    #         time += deltaT
    #
    #     # First invoice is generated by the product, so skip to the second invoice here
    #     time += deltaT
    #
    #     return fields.Date.to_string(time)


class ContractTemplateLine(models.Model):
    _inherit = "contract.template.line"

    sale_order_line_id = fields.Many2one(comodel_name='sale.order.line')